In [7]:
# Imports
import numpy as np 
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import random
from sklearn import preprocessing
import scipy.optimize as op
from utils import mnist_reader
%matplotlib inline
      
# Each row is a training example, each column is a feature  [X1, X2, X3]
#X=np.array(([0,0,1],[0,1,1],[1,0,1],[1,1,1]), dtype=float)
#y=np.array(([0],[1],[1],[0]), dtype=float)

X_train, y_train = mnist_reader.load_mnist('data/fashion', kind='train')
X_test, y_test = mnist_reader.load_mnist('data/fashion', kind='t10k')




# Normalize Test

X_test_scaled = norm.fit_transform(X_test)
df_normalized_test = pd.DataFrame(X_test_scaled)



print('Training data normalized shape' , X_test_scaled.shape)


print('Training data normalized shape' ,X_train_scaled.shape)

# Define useful functions    

# Activation function
def sigmoid(t):
    return 1/(1+np.exp(-t))

# Derivative of sigmoid
def sigmoid_derivative(p):
    return p * (1 - p)

# Class definition
class NeuralNetwork:
    def __init__(self, x,y):
        self.input = x
        self.weights1= np.random.rand(self.input.shape[1],4) # considering we have 4 nodes in the hidden layer
        self.weights2 = np.random.rand(4,1)
        self.y = y
        self.output = np. zeros(y.shape)
        
    def feedforward(self):
        self.layer1 = sigmoid(np.dot(self.input, self.weights1))
        self.layer2 = sigmoid(np.dot(self.layer1, self.weights2))
        return self.layer2
        
    def backprop(self):
        d_weights2 = np.dot(self.layer1.T, 2*(self.y -self.output)*sigmoid_derivative(self.output))
        d_weights1 = np.dot(self.input.T, np.dot(2*(self.y -self.output)*sigmoid_derivative(self.output), self.weights2.T)*sigmoid_derivative(self.layer1))
    
        self.weights1 += d_weights1
        self.weights2 += d_weights2

    def train(self, X, y):
        self.output = self.feedforward()
        self.backprop()
        

NN = NeuralNetwork(X_test_scaled,y_train)

for i in range(1500): # trains the NN 1,000 times
    if i % 100 ==0: 
        print ("for iteration # " + str(i) + "\n")
        print ("Input : \n" + str(X_test_scaled))
        print ("Actual Output: \n" + str(y_train))
        print ("Predicted Output: \n" + str(NN.feedforward()))
        #print ("Loss: \n" + str(np.mean(np.square(y_train - NN.feedforward())))) # mean sum squared loss
        print ("\n")
  
    NN.train(X_test_scaled, y_train)

Training data normalized shape (10000, 784)
Training data normalized shape (60000, 784)
for iteration # 0

Input : 
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
Actual Output: 
[9 0 0 ... 3 0 5]
Predicted Output: 
[[0.75225993]
 [0.75225993]
 [0.75225993]
 ...
 [0.75225993]
 [0.75225993]
 [0.75225993]]




ValueError: array is too big; `arr.size * arr.dtype.itemsize` is larger than the maximum possible size.