# Neural Network 

## Juan Fernando Gonzalez
20170085

## Libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import random
from sklearn import preprocessing
import scipy.optimize as op
from utils import mnist_reader
%matplotlib inline

## Neural Network Implementation

### Sigmoid Function

In [2]:
def sigmoid(x):
    """
    
    Returns the sigmoid activation of a given input.
    
    """
    
    s = (1/(1 + np.e**(-x)))
    
    return s

### Feed Forward Function

In [3]:
def feed_forward2(thetas, X):
    
    """
    Returns the all activations of all neurons of a layer.
    
    activations:
        array: Keep the activation given the sigmoid function. (vector)
    Bias:
        Bias added to our activations. (vector)
    thetas: 
        Weight of each connection. (Matrix)
    
    """
    
    activations = []
    activations.append(X)                     # Input Neurons (layer 0)
    bias = np.ones(len(X)).reshape(len(X), 1) # Bias added (vector of ones) 
    
    for i in range (len(thetas)):
        
        print('A:',activations[i])            # Actual activation 
        print('Thetas',thetas[i])             # Actual Theta
        print('Shape',thetas[i].shape)        # Shape of the actual theta
        
                                   # np.dot(activations(with bias), current_theta(weigh))
        activations.append(sigmoid(np.dot(np.hstack((bias, activations[i])), thetas[i].T))) 
        
        print('Current Activation: \n' , activations[i])
    
    return activations

In [4]:
def feed_forward(thetas, X):
    
    """
    Returns the all activations of all neurons of a layer.
    
    activations:
        array: Keep the activation given the sigmoid function. (vector)
    Bias:
        Bias added to our activations. (vector)
    thetas: 
        Weight of each connection. (Matrix)
    
    """
    
    activations = []
    activations.append(X)                     # Input Neurons (layer 0)
    bias = np.ones(len(X)).reshape(len(X), 1) # Bias added (vector of ones) 
    
    for i in range (len(thetas)):
        
        print('A:',activations[i])            # Actual activation 
        print('Thetas',thetas[i])             # Actual Theta
        print('Shape',thetas[i].shape)        # Shape of the actual theta
        
                                   # np.dot(activations, current_theta(weigh) + bias)
        activations.append(sigmoid(np.dot(activations[i], thetas[i]) + bias))
        
        print('Current Activation: \n' , activations[i + 1], '\n')
        print('\t --------------------------------------------------------------------- \n')
    
    return activations

### Cost Function

In [5]:
def cost_function(act, Y):
    
    m = Y.shape[1]
    
    cost = (-1/m) * (np.dot(np.log(A), Y.T) + np.dot(log(1 - A), 1 - Y.T)) 
    
    return cost

### Back Propagation Function

In [6]:
def back_prop(act, X, Y):
    
    
    
    pass

### Thetas calculation

In [7]:
def brain_thatas(layer_dims):
    
    np.random.seed(1)
    
    thetas = []
    
    L = len(layer_dims)
    
    for l in range(1, L):
        
        thetas.append(np.random.randn(layer_dims[l], layer_dims[l - 1]) * 0.01)

        
    return thetas

## Load Data

In [8]:
X_train, y_train = mnist_reader.load_mnist('data/fashion', kind='train')
X_test, y_test = mnist_reader.load_mnist('data/fashion', kind='t10k')

In [9]:
X_train.shape

(60000, 784)

In [10]:
X_test.shape

(10000, 784)

### Normalize Data

#### Train data

In [11]:
# Normalize

norm = preprocessing.MinMaxScaler()

X_train_scaled = norm.fit_transform(X_train)
df_normalized_train = pd.DataFrame(X_train_scaled)

print('Training data normalized shape' ,X_train_scaled.shape)

Training data normalized shape (60000, 784)


#### Test data

In [12]:
# Normalize

X_test_scaled = norm.fit_transform(X_test)
df_normalized_test = pd.DataFrame(X_test_scaled)

print('Training data normalized shape' , X_test_scaled.shape)

Training data normalized shape (10000, 784)


## Data Input

### Input Layer

In [13]:
X = np.array([[0, 0, 1],
             [1, 1, 1],
             [1, 0, 1],
             [0, 1, 1]])

In [14]:
X.shape

(4, 3)

### Output layer

In [15]:
Y = np.array([0, 1, 1, 0]).T

Y.shape

(4,)

### Hidden Layers

In [16]:
hiddenL_1 = np.zeros((3, 1))

hiddenL_2 = np.zeros((2, 1))

### Network Architecture

In [33]:
#Total Layers =  input_l + hidden_layers + output_l

total_l = []
total_l.append(len(X))
total_l.append(len(hiddenL_1))
#total_l.append(len(hiddenL_2))
total_l.append(len(Y))

In [34]:
print('Dimensions: ', total_l)  

Dimensions:  [4, 3, 4]


### Weights (Thetas)

In [39]:

thetas = brain_thatas(total_l)

for i in range (len(thetas)):
    print('Theta (' + str(i) +'): \n', thetas[i])
    print('\t\tShape: ',  thetas[i].shape, '\n')

Theta (0): 
 [[ 0.01624345 -0.00611756 -0.00528172 -0.01072969]
 [ 0.00865408 -0.02301539  0.01744812 -0.00761207]
 [ 0.00319039 -0.0024937   0.01462108 -0.02060141]]
		Shape:  (3, 4) 

Theta (1): 
 [[-0.00322417 -0.00384054  0.01133769]
 [-0.01099891 -0.00172428 -0.00877858]
 [ 0.00042214  0.00582815 -0.01100619]
 [ 0.01144724  0.00901591  0.00502494]]
		Shape:  (4, 3) 



## Feed Forward - Get activations 

In [37]:
print('Activations: \n' ,feed_forward(thetas, X))

A: [[0 0 1]
 [1 1 1]
 [1 0 1]
 [0 1 1]]
Thetas [[ 0.01624345 -0.00611756 -0.00528172 -0.01072969]
 [ 0.00865408 -0.02301539  0.01744812 -0.00761207]
 [ 0.00319039 -0.0024937   0.01462108 -0.02060141]]
Shape (3, 4)
Current Activation: 
 [[0.73168538 0.730568   0.73392353 0.72698887]
 [0.73654503 0.72479515 0.73629261 0.72333335]
 [0.7348623  0.72936214 0.73289084 0.7248541 ]
 [0.73338096 0.72601373 0.73731686 0.72547545]] 

	 --------------------------------------------------------------------- 

A: [[0.73168538 0.730568   0.73392353 0.72698887]
 [0.73654503 0.72479515 0.73629261 0.72333335]
 [0.7348623  0.72936214 0.73289084 0.7248541 ]
 [0.73338096 0.72601373 0.73731686 0.72547545]]
Thetas [[-0.00322417 -0.00384054  0.01133769]
 [-0.01099891 -0.00172428 -0.00877858]
 [ 0.00042214  0.00582815 -0.01100619]
 [ 0.01144724  0.00901591  0.00502494]]
Shape (4, 3)
Current Activation: 
 [[0.73071187 0.73238601 0.73055843]
 [0.73071324 0.73238055 0.7305705 ]
 [0.73070757 0.73237907 0.73056773]
